version: '3'

services:

  rifatu-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rifatu-api
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    links:
      - rifatu-mongo
    depends_on:
      - rifatu-mongo

  
  rifatu-mongo:
    image: mongo:latest
    container_name: rifatu-mongo
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo:/data/db
    ports:
      - '6000:27017'

volumes:
  mongo:
