version: '3'

services:

  rifatu-api:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rifatu-api
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    networks:
      - rifiatu_api
    links:
      - mongo
    depends_on:
      - mongo

  
  mongo:
    image: mongo:4.4.18
    container_name: mongo
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
    volumes:
      - mongo:/data/db
    ports:
      - '27017:27017'
    networks:
      - rifiatu_api

volumes:
  mongo:

networks:
  rifiatu_api:
    driver: bridge
